### ISSUE TITLE
Background not working

### ISSUE THREAD

**Issue by splace** [vrml2/tnakgame#1]
values of Sky angle not right

**Comment by splace** [comment]
sky angle has faulty decreasing angle, not sure what it was meant to be?
```
Background { 
  skyColor [ 
    0.96 1.00 1.00
    0.80 0.91 1.00
    0.67 0.76 0.85
    0.56 0.64 0.71
  ] 
#  skyColor [ 
#    0.56 0.64 0.71
#    0.56 0.64 0.71
#    0.56 0.64 0.71
#    0.56 0.64 0.71
#  ] 
  skyAngle [ 1.571 1.658 1.833 1.745 ] 
} 

```

**Comment by dwblaikie** [comment]
ah - it's meant to give a nice blue sky kind of feeling - so I imagine it should be a smooth/continuous gradient in one direction or the other, however the angles/color work. So maybe swapping the last two angles and leave it at that?

**Comment by splace** [comment]
fixed
