### ISSUE TITLE
lighting angle odd

### ISSUE THREAD

**Issue by splace** [vrml2/tnakgame#4]
underside and mountain sides dark

**Comment by splace** [comment]
seems to fit with directional light direction

```
          children [
            DirectionalLight {
              direction -.3 -1 -.3 
            }
            DEF exp ExplosionManager {
            }
            DEF tm TankManager {   
            },
            DEF ter Terrain {  
            },
            DEF proj Projectile {
            }
          ]
```

**Comment by dwblaikie** [comment]
Yeah, the idea was to be sort of like sunlight - so the underside of the terrain should be unlit, and some steep mountains might be unlit on one side.

That said, perhaps a little ambient (or a lower directly down light) might help so the mountain shadows aren't such a stark contrast.
